//Networking Macros
#macro NETWORK_EVENT_BROADCAST 0
#macro NETWORK_EVENT_PING 1
#macro NETWORK_EVENT_MOVE 2
#macro NETWORK_EVENT_DISCONNECT 3
#macro NETWORK_EVENT_USERNAME 4
#macro NETWORK_EVENT_CHAT 5
#macro NETWORK_EVENT_BULLET 6
#macro NETWORK_EVENT_HIT 7
#macro NETWORK_EVENT_LOGIN 8
#macro NETWORK_EVENT_DEAD 9
#macro NETWORK_EVENT_GAMEOVER 10
#macro NETWORK_EVENT_GAMERESET 11

#macro NETWORK_SUCCESS 0
#macro NETWORK_FAILURE 1

//Camera Macros
#macro SHAKE_MAGNITUDE 10

//Gamestate Macros
#macro GAMESTATE_PLAYING 0
#macro GAMESTATE_ENDED 1

//Gameplay Macros
#macro SHOT_SPEED 20
#macro TEAM_A 0
#macro TEAM_B 1
#macro MAX_HP 5
#macro GAMEMODE_TDM 0
#macro GAMEMODE_CPS 1
#macro HEALING_RATE 1
#macro WINNING_SCORE_TDM 30

//Button Macros
#macro TEXT_IPADDRESS 1
#macro TEXT_PORT 2
#macro TEXT_MAX_CLIENTS 3
#macro TEXT_SERVER_NAME 4
#macro TEXT_USERNAME 5
#macro TEXT_PASSWORD 6
#macro TEXT_WINNING_SCORE 7
#macro BUTTON_JOIN 1
#macro BUTTON_CREATE 2
#macro BUTTON_USERNAME 3

//Level Macros
#macro LEVEL_ONE 1
#macro LEVEL_TWO 2
